name: Go

on:
  push:
    branches: [thai]
  pull_request:
    branches: [thai]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/725356851529/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'go-tour-th@appspot.gserviceaccount.com'
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        project_id: ${{ secrets.project_id }}
        working_directory: tour
