name: Go

on:
  push:
    branches: [thai]
  pull_request:
    branches: [thai]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - id: Deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: ${{ secrets.project_id }}
          working_directory: tour
